workers:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 800m
      memory: 1Gi
  
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 2Gi

  logGroomerSidecar:
    enabled: false

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  startupProbe:
    timeoutSeconds: 60
    periodSeconds: 10
    failureThreshold: 12
  
  logGroomerSidecar:
    enabled: false

apiServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  startupProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
    failureThreshold: 10
    periodSeconds: 10
  
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 30
  
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 10

webserver:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
    
  startupProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 30
    failureThreshold: 10
    periodSeconds: 10
  
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 30
  
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 10

triggerer:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi 
  
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 1Gi

  logGroomerSidecar:
    enabled: false

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 1Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClassName: "standard"
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi

flower:
  enabled: false

statsd:
  enabled: false

pgbouncer: 
  enabled: false

cleanup:
  enabled: false

config:
  core:
    # Reduce parallelism for lower resource usage
    parallelism: 8         # Further reduced
    max_active_tasks_per_dag: 4  # Further reduced
    max_active_runs_per_dag: 1
    # Disable example DAGs
    load_examples: 'False'
    # Reduce startup time
    check_slas: 'False'
    store_dag_code: 'True'
    store_serialized_dags: 'True'

  celery:
    worker_concurrency: 2
  
  scheduler:
    # Reduce scheduler intervals to save CPU
    scheduler_heartbeat_sec: 10
    min_file_process_interval: 30
    dag_dir_list_interval: 300
    # Reduce parsing processes for faster startup
    parsing_processes: 1
    max_dagruns_to_create_per_loop: 5
    max_dagruns_per_loop_to_schedule: 10

  webserver:
    workers: 1
    worker_refresh_batch_size: 1
    reload_on_plugin_change: 'False'
    update_fab_perms: 'False'

  api: 
    enable_experimental_api: 'False'

# airflow:
#   extraPipPackages:
#     - pyyaml
#     - requests
#     - boto3